### ISSUE TITLE
Json file is required with the structure

### ISSUE THREAD

**Issue by Sonu2396** [ykara61/Unofficial-Investing-com-Alarm#1]
Please share this json file and its structure required for reading the instrument's names. 
Json file is required with the structure

**Comment by ykara61** [comment]
Sure, I will share it in a day. Thank you for feedback.

**Comment by ykara61** [comment]
Hello, I have fixed the issue. However, if you still want to now json structure, I will share it below.

`[{"Name":"ExampleName","LinkString":"https://example.com/"}]`

**Comment by Sonu2396** [comment]
Hi
Tha for the update.
Can you share a ticket example from investing.com. the symbol name and url .
Which exact url we should put over there.

Have you also used amibroker?

Do you have any trading strategies which can make good returns?

Do you want to connect to write some automated trading strategies?

If any of these are of interest to you, let's connect.

Regards
Surendra Choudhary

**Comment by Sonu2396** [comment]
Please share an example of the URL and Instrument name. 
I am not sure what exact URL must be provided.

**Comment by ykara61** [comment]
> Please share an example of the URL and Instrument name. I am not sure what exact URL must be provided.

You can use any instrument name you want and You can use direct **btc-usd** URL (such as; Instrument label = "BTC/USD" and Link="https://www.investing.com/crypto/bitcoin/btc-usd").
